# GENERATED by the SkyRoads analysis toolkit.
# Loads one levels/road_NN.json produced by `sra export-godot`.
class_name RoadData
extends Resource

@export var index: int
@export var rows: int
@export var gravity: int          ## header word 1; dashboard shows (g-3)*100
@export var fuel_rows: int        ## header word 2: rows a full tank covers
@export var oxygen_secs: int      ## header word 3: seconds a full tank lasts
@export var world: int            ## WORLDn backdrop
@export var cells: PackedInt32Array   ## rows * 7 tile codes, row 0 = start
@export var palette: PackedColorArray ## 72 road colours


static func load_json(path: String) -> RoadData:
	var f := FileAccess.open(path, FileAccess.READ)
	assert(f != null, "missing road json: " + path)
	var d: Dictionary = JSON.parse_string(f.get_as_text())
	var r := RoadData.new()
	r.index = d.index
	r.rows = d.rows
	r.gravity = d.gravity
	r.fuel_rows = d.fuel_rows
	r.oxygen_secs = d.oxygen_secs
	r.world = d.world
	r.cells = PackedInt32Array(d.cells)
	r.palette = PackedColorArray()
	for c in d.palette:
		r.palette.append(Color8(c[0], c[1], c[2]))
	return r


func tile(row: int, col: int) -> int:
	return cells[row * 7 + col]


## Y of the surface the ship rests on for this cell, in original units.
func top_height(row: int, col: int) -> int:
	return SkyRoads.tile_top_height(tile(row, col))
