# GENERATED by the SkyRoads analysis toolkit — do not edit by hand.
# Source of truth: analysis/sra/consts.py, itself quoted against
# SKYROADS.EXE instruction addresses (see skyroads-port/re/notes/).
#
# The original game is pure integer maths at a fixed 36.0036 Hz tick. Keep the
# simulation in these units and convert to metres/seconds only for rendering,
# or the feel changes.
class_name SkyRoads
extends RefCounted


const AIR_STEER_WINDOW = 3840
const AP_LIGHT_POS = [203, 156]
const AP_STRENGTHS = 6
const AP_TRIGGER_Y = 14080
const ATTRACT_IDLE_TICKS = 360
const BLOCK_TOP = [10240, 12800, 12800, 12800, 15360, 15360]
const BOUNCE_DEN = 10
const BOUNCE_NUM = 5
const BOUNCE_THRESH_DEN = 8
const BOUNCE_THRESH_NUM = 260
const CARS_EXPLOSION_FRAMES = 14
const CARS_INDEX_FORMULA = "14 + 9*tilt + 3*pitch + flame"
const CARS_SHIP_FRAMES = 63
const CARS_SPRITE_BYTES = 720
const CARS_SPRITE_H = 30
const CARS_SPRITE_W = 24
const CFG_BYTES = 66
const CFG_CHECKSUM = "sum over i=1..32 of (word[i] XOR i); mismatch zeroes the file"
const CFG_LAYOUT = ["checksum", "control_device", "sound_off", "completions[0]", "completions[1]", "completions[2]", "completions[3]", "completions[4]", "completions[5]", "completions[6]", "completions[7]", "completions[8]", "completions[9]", "completions[10]", "completions[11]", "completions[12]", "completions[13]", "completions[14]", "completions[15]", "completions[16]", "completions[17]", "completions[18]", "completions[19]", "completions[20]", "completions[21]", "completions[22]", "completions[23]", "completions[24]", "completions[25]", "completions[26]", "completions[27]", "completions[28]", "completions[29]"]
const CFG_WORDS = 33
const COLS = 7
const COL_W = 5888
const CONTROL_DEVICE = {0: "keyboard", 1: "joystick", 2: "mouse"}
const CORNER_NUDGE = 928
const DASH_PICT_Y = 129
const DATA_FILES = ["ROADS.LZS", "TREKDAT.LZS", "CARS.LZS", "DASHBRD.LZS", "MUZAX.LZS", "MAINMENU.LZS", "SETMENU.LZS", "HELPMENU.LZS", "GOMENU.LZS", "INTRO.LZS", "ANIM.LZS", "WORLD0.LZS", "WORLD1.LZS", "WORLD2.LZS", "WORLD3.LZS", "WORLD4.LZS", "WORLD5.LZS", "WORLD6.LZS", "WORLD7.LZS", "WORLD8.LZS", "WORLD9.LZS", "SFX.SND", "INTRO.SND", "DEMO.REC", "FUL_DISP.DAT", "OXY_DISP.DAT", "SPEED.DAT"]
const DEATH_HOLD = 108
const DECK_SOLID_HI = 10240
const DECK_SOLID_LO = 7808
const DEMO_BYTES_PER_SAMPLE = 1638
const EDGE_PROBE_MAX = 14
const EDGE_PROBE_STEP = 128
const EDGE_PUSH = 17
const EXPL_FRAMES = 42
const EXPL_YVEL_CAP = 71
const EXPL_YVEL_STEP = 39
const FADE_TICKS = 36
const FLAME_TABLE = [0, 1, 2, 1]
const FLY_AWAY = 72
const GAME_PALETTE_BASES = {"CARS.LZS": [72], "DASHBRD.LZS": [92], "WORLDn.LZS": [142], "ROADS.LZS": [0]}
const GAUGE_SEGMENTS = 10
const GAUGE_UNITS_PER_SEG = 3000
const GEOMETRY = {0: "flat", 1: "tunnel", 2: "block_half", 3: "block_half_bore", 4: "block_full", 5: "block_full_bore"}
const GEOM_HEIGHT_CLASS = [1, 2, 3, 3, 4, 4, 1, 1]
const GOMENU_TICKS_MAX = 7
const GRAVITY_DIGITS = 4
const GRAVITY_POS = [96, 156]
const GRAV_DIV = 400
const GRAV_MUL = 5760
const HAZARDS = ["burning"]
const HELPERS = ["boost", "supplies"]
const HORIZON_Y = 32
const HUD_COLORS = {"seg_lit": [94, 95], "seg_unlit": [92, 93], "progress": 96, "digit": [97, 98], "ap_light": 98, "warn_swap": [99, 100], "text": 99}
const INTRO_ANIM_TICK = 61
const INTRO_SND_TICK = 24
const JUMP_MAX_GRAVITY = 20
const JUMP_VEL = 1152
const LATERAL_BONUS = 1560
const LATERAL_DIV = 512
const MAX_ROWS = 500
const MENU_PALETTE_BASES = {"MAINMENU.LZS": [190], "SETMENU.LZS": [200, 250], "HELPMENU.LZS": [200], "GOMENU.LZS": [0, 240], "INTRO.LZS": [0]}
const OXY_TICK_DIV = 36
const PALETTE_BASES = {"road": [0, 72], "cars": [72, 20], "dashboard": [92, 50], "world": [142, 114]}
const PHASE_ROW_OFFSCREEN = 158
const PHASE_ROW_TOPS = [[32, 34, 37, 41, 46, 52, 61, 76, 102], [34, 35, 38, 41, 46, 53, 63, 79, 107], [34, 35, 38, 42, 47, 54, 65, 81, 112], [34, 35, 39, 43, 48, 55, 66, 84, 118], [34, 36, 39, 43, 49, 56, 68, 87, 124], [34, 36, 39, 44, 49, 58, 70, 91, 158], [34, 37, 40, 44, 50, 59, 72, 94, 158], [34, 37, 40, 45, 51, 60, 74, 98, 158]]
const PITCH_VEL_THRESHOLD = 355
const PIXEL_ASPECT = 1.2
const PROGRESS_STEPS = 30
const PROGRESS_X = 42
const PROGRESS_Y = 143
const RESULT = {-1: "running", 0: "complete", 1: "crashed_into_wall", 2: "burned", 3: "fell_off", 4: "out_of_fuel", 5: "out_of_oxygen", 7: "quit"}
const ROADS_COUNT = 31
const ROAD_PALETTE_LAYOUT = {"floor": [1, 14], "floor_front": [16, 29], "side_left": [31, 45], "side_right": [46, 60], "block_default": [61, 61], "block_top": [62, 62], "block_side": [63, 64], "tunnel_wall": [65, 67], "tunnel_arch": [68, 73]}
const SCREEN_H = 200
const SCREEN_W = 320
const SCROLL_PHASES = 8
const SFX = {0: "explosion", 1: "bounce_thud", 2: "bump_scrape", 3: "warning_beep", 4: "supplies_refill"}
const SFX_BUSY_TICKS = 8
const SHADOW_DARKEN = 45
const SHADOW_H = 9
const SHADOW_MAPS = 5
const SHADOW_PROBE_X = 896
const SHADOW_W = 29
const SHIP_BAND_COL_EDGES = [58, 87, 116, 146, 160]
const SHIP_BAND_PHASE = 0
const SHIP_DIR_ROW = 7
const SHIP_DRAW_H = 24
const SHIP_DRAW_W = 29
const SHIP_HALF_W = 1792
const SHIP_PAN = [-1, -1, -1, 0, 1, 2, 4]
const SHIP_SCREEN_Y_BASE = 157
const SHIP_SPRITE_ORIGIN_X = 110
const SONG_ROLES = {0: "title/intro", 1: "menu", 2: "gameplay", 3: "gameplay", 4: "gameplay", 5: "gameplay", 6: "gameplay", 7: "gameplay", 8: "gameplay", 9: "gameplay", 10: "gameplay", 11: "gameplay", 12: "gameplay", 13: "gameplay"}
const SPEEDO_SEGMENTS = 34
const SPEEDO_UNITS_PER_SEG = 321
const SPEED_ACCEL = 75
const SPEED_BOOST = 303
const SPEED_KILL = 3640
const SPEED_MAX = 10922
const SPEED_SCRAPE = 151
const SPEED_STICKY = 303
const SQUARE_H = 240
const STEER_VEL = 29
const SUPPLY_SFX_THRESH = 27000
const SURFACE = {0: "void", 2: "sticky", 8: "ice", 9: "supplies", 10: "boost", 12: "burning"}
const TANK_FULL = 30000
const TICK_DEN = 33140
const TICK_HZ = 36.00428485
const TICK_NUM = 1193182
const TILE_BLOCKTOP_MASK = 240
const TILE_GEOM_MASK = 3840
const TILE_SURFACE_MASK = 15
const TILE_UNUSED_MASK = 61440
const TUN_INNER = [16, 16, 16, 16, 15, 14, 13, 11, 8, 7, 6, 5, 3, 3, 3, 3, 3, 3, 2, 1, 0, 0, 0, 0, 0, 0, 1, 2, 3, 3, 3, 3, 3, 3, 5, 6, 7, 8]
const TUN_OUTER = [32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 31, 31, 31, 31, 31, 30, 30, 30, 29, 29, 29, 28, 27, 26, 25, 24, 22, 20, 18, 17, 14]
## The rows the road can occupy: VIEW_TOP..VIEW_H-1 of the original's screen.
##
## The DOS framebuffer viewport starts at row 32 (render.c: `fb->px + 32*320`),
## but no band record ever reaches above row 34 — the farthest boundary, seven
## rows ahead of the ship, lands there. Checked against the C engine across a
## run: rows 32 and 33 are the world picture and nothing else, at every tick,
## while rows 34+ carry road. So 34 is the real bound, and it is the one that
## matters here: this engine's camera has no such limit, and a tall block a
## few rows ahead projects its top well above the horizon, appearing out of
## the sky before its body arrives.
const VIEW_TOP = 34
const VIEW_H = 138
const VISIBLE_ROWS = 10
const VOID_FALL_VEL = -106
const WARN_BLINK_PERIOD = 9
const WARN_FUEL_RECT = [155, 169, 16, 5]
const WARN_OXY_RECT = [160, 161, 7, 7]
const WORLDS_COUNT = 10
const X_MAX = 53376
const X_MIN = 12160
const X_START = 32768
const Y_DECK = 10240
const Y_FULL = 15360
const Y_HALF = 12800
const Z_START_ROW = 3


static func grav_accel(gravity: int) -> int:
	# -(g * 0x1680 / 0x190) = -14.4*g per tick  (EXE 0x1f4d)
	return -((gravity * GRAV_MUL) / GRAV_DIV)


static func bounce_threshold(gravity: int) -> int:
	return (BOUNCE_THRESH_NUM * gravity) / BOUNCE_THRESH_DEN


static func dash_gravity(gravity: int) -> int:
	return (gravity - 3) * 100


static func tile_surface(code: int) -> int:
	return code & TILE_SURFACE_MASK


static func tile_blocktop(code: int) -> int:
	return (code >> 4) & TILE_SURFACE_MASK


## True on a real phone or tablet. Deliberately narrower than
## `OS.has_feature("mobile")`, which is also true for a web export on a
## touch device: the mobile UI changes here — no Controls item, no keyboard
## hints, a pause button instead of the P key — are for Android and iOS
## specifically, and the desktop build must never take them.
static func is_mobile() -> bool:
	var n := OS.get_name()
	return n == "Android" or n == "iOS"


static func tile_geometry(code: int) -> int:
	return (code >> 8) & TILE_SURFACE_MASK


static func tile_top_height(code: int) -> int:
	var g := tile_geometry(code)
	return BLOCK_TOP[g] if g < BLOCK_TOP.size() else Y_DECK
