# Camera constants for the SkyRoads port.
#
# ORIGINALLY generated by the analysis toolkit's pinhole fit; REPLACED
# 2026-08-30 after the fit was refuted by decoding the actual TREKDAT span
# tables through the C reference engine (tools/dump_bands.c). The measured
# ground truth, phase 0, absolute 200-line screen coordinates:
#
#   band edges (boundary k rows ahead of the ship's z):
#     k:  +7  +6  +5  +4  +3  +2  +1   0
#     y:  34  37  41  46  52  61  76  102
#   least-squares pinhole through those edges (rms 0.24 px):
#     y200(d) = 9.569 + 235.636 / d,  camera 2.550 rows behind the ship,
#     camera height exactly 1.0 row-units above the deck.
#
#   horizontal: the lane edges are STRAIGHT LINES through a vanishing point
#   at y200 = 32 (the viewport top), lane width = (2/3) * (y200 - 32) px —
#   46 px/lane at the ship's deckline (y=101), which is exactly the 46
#   px/lane the collision code uses. This cone is deliberately inconsistent
#   with the vertical pinhole (vanishing y 32 vs 9.57): the DOS table is a
#   hand-built fake perspective, so NO physical camera reproduces both.
#
# The camera below implements the vertical pinhole exactly; the horizontal
# cone is applied as a vertex-shader warp on every road material
# (make_dos_material), scaling view-space X by dos_x_scale(depth) so the
# projected lane width follows the DOS cone at every depth.
#
# The previous constants (FOCAL 279.7, BEHIND 3.535) put the camera a full
# row too far back — the world was drawn misaligned against the DOS-exact
# ship blit at every depth except the one the old fit anchored, which is
# what "the collisions are offset" was.
class_name SkyRoadsCamera
extends Camera3D

## One grid row of depth = 1.0 world unit. Everything below follows from that.
## 240-canvas pixels: FOCAL = 235.636 * 1.2, PRINCIPAL.y = 9.569 * 1.2.
const FOCAL_PX := 282.7632
const CANVAS := Vector2(320, 240)
const PRINCIPAL := Vector2(160.0, 11.4826)
const VFOV_DEG := 46.0170
const HFOV_DEG := 59.0791
const CAMERA_HEIGHT := 1.0000    ## above the road deck (measured exact)
const BEHIND_ROWS := 2.5500      ## distance back from the ship's z
## 46 px/lane at the ship's depth: 46 * BEHIND_ROWS / FOCAL_PX.
const COLUMN_WIDTH := 0.414855
const ROAD_WIDTH := 2.903985
const PIXEL_ASPECT := 1.2000     ## mode 13h pixels are taller than wide

## Game Y units (deck = 0x2800, 0x80 per screen pixel) -> world units:
## one original pixel = PIXEL_ASPECT canvas px = PIXEL_ASPECT*BEHIND/FOCAL.
const WORLD_PER_GAME_Y := 0.0000845441
const DECK_Y := 0.0
const HALF_BLOCK_Y := 0.216433
const FULL_BLOCK_Y := 0.432866

## The DOS horizontal cone, in the 200-line table space.
const DOS_F200 := 235.636
const DOS_P200 := 9.569
const DOS_X_VANISH_Y := 32.0
const DOS_LANE_PER_LINE := 2.0 / 3.0

@export var near_plane := 0.05
@export var far_plane := 200.0


func _ready() -> void:
	apply_original_framing()


## Frustum with the principal point off centre. Godot builds the frustum at the
## near plane, so both size and offset scale with it: a view FOCAL_PX pixels
## from the eye spans CANVAS.y pixels, hence CANVAS.y * near / FOCAL_PX metres.
func apply_original_framing() -> void:
	var size := CANVAS.y * near_plane / FOCAL_PX
	var offset_px := CANVAS.y * 0.5 - PRINCIPAL.y   ## +ve = principal above centre
	# Godot ADDS the offset to both frustum edges, so a negative offset.y
	# slides the visible band downward — the principal point sits near the top
	# of the frame and the road lies below the camera.
	var offset := Vector2(0.0, -offset_px * near_plane / FOCAL_PX)
	set_frustum(size, offset, near_plane, far_plane)


## The road does not scroll continuously in the original. render.c takes
## `pos = z / 0x2000` — eight steps per grid row — and uses `pos & 7` to pick
## one of EIGHT baked band tables, so the world is presented at one of eight
## positions per row and nothing in between. The tables say so directly
## (`tools/dump_bands.c lines`): the ship's own row occupies screen rows
## 76..101 at phase 0 and 84..117 at phase 3, and there is no table for a
## position between them.
##
## A continuous camera therefore drifts from the reference by up to an eighth
## of a row, which is nothing at the horizon and largest in the near field,
## where dy/dd is. Quantising is worth a little, and it is worth it on both
## metrics — road 21 t=200 measured with the surface map and with RGB:
##
##     scroll quantised    sid 13.7% differ    RGB 8.6% at tol 16
##     continuous          sid 14.1%           RGB 9.0%
##
## That is the whole of its effect. An earlier version of this comment claimed
## the quantisation WAS the near-field defect of BUGS §12.14; the A/B above
## refutes that. The defect survives it almost untouched (the misattributed
## band goes from 1685 px to 1633), and §12.15 attributes it properly.
const SCROLL_PHASES := 8.0

static func dos_scroll_row(row: float) -> float:
	return floor(row * SCROLL_PHASES) / SCROLL_PHASES


## Place the camera for a ship at `row` (fractional grid rows travelled).
func follow(row: float) -> void:
	position = Vector3(0.0, CAMERA_HEIGHT, -(row - BEHIND_ROWS))
	rotation = Vector3.ZERO        ## the original never pitches or rolls


## Centre of grid cell (row, col) on the deck. Column 3 is the middle lane.
static func cell_centre(row: int, col: int) -> Vector3:
	return Vector3((col - 3.0) * COLUMN_WIDTH, 0.0, -float(row))


## The VERTICAL twin of the cone below: how much SHORTER or taller the
## original draws a raised surface than this pinhole does, at `depth`.
##
## The camera is a least-squares pinhole through the DECK band edges and it
## reproduces those to 0.24 px. Raised surfaces are not on it. Measured off the
## baked span tables (`tools/dump_bands.c kindlines <k>`, record 0 — the block
## tier — at the lane centre x=159, every phase 0..7 and every band dr0..dr9),
## the tier's apparent height above the deck as a fraction of the height this
## camera gives it:
##
##     depth   0.80  1.05  1.55  2.05  2.55  3.55  4.55  5.55  6.55
##     g       1.41  1.29  1.16  1.08  1.00  0.87  0.73  0.60  0.48
##
## The half-height block (kind 2) and the full-height block (kind 5) give the
## same numbers to within the one screen row the tables are quantised to, so g
## is a function of DEPTH ALONE and not of height — which is what makes it a
## vertex scale rather than a per-kind fudge. It passes through exactly 1.0 at
## BEHIND_ROWS, the ship's own depth: the block beside the ship is where the
## pinhole puts it, and everything else is drawn flatter or taller than
## perspective would draw it.
##
## a + b*d + c/d is the best of the closed forms tried (rms 0.015 over
## d in [0.8, 7]; a + b*d alone is 0.031, a + b/d is 0.116). BUGS.md §12.18.
const DOS_TIER_A := 1.23112
const DOS_TIER_B := -0.12108
const DOS_TIER_C := 0.19879
## Below this the original draws nothing — the nearest band's near edge is off
## the bottom of the composed window — and g would run away.
const DOS_TIER_MIN_DEPTH := 0.80


## The factor to scale a vertex's height above the deck by, at `depth`.
static func dos_y_scale(depth: float) -> float:
	var d := maxf(depth, DOS_TIER_MIN_DEPTH)
	return maxf(DOS_TIER_A + DOS_TIER_B * d + DOS_TIER_C / d, 0.0)


## How much wider/narrower the DOS cone draws a lane at `depth` than this
## camera's pinhole does. Applied to view-space X by the road shader; use it
## anywhere screen X of ROAD geometry is computed on the CPU (labels).
static func dos_x_scale(depth: float) -> float:
	var d := maxf(depth, 0.05)
	var y200 := DOS_P200 + DOS_F200 / d
	var dos_lane := maxf(DOS_LANE_PER_LINE * (y200 - DOS_X_VANISH_Y), 0.001)
	var pin_lane := 46.0 * BEHIND_ROWS / d
	return dos_lane / pin_lane


## Where the original splits the ship's own grid row: render.c:361-396 draws
## that row as "pre-ship" (dirbase 0x210) geometry, then the sprite, then
## "post-ship" (0x240). Decoding the two directories shows the cut is the
## fixed screen line y200 = 102, and 235.636 / (102 - 9.569) = 2.550 — the
## ship's own depth. So the rule is simply: geometry NEARER than the ship
## paints over it, geometry beyond it does not.
const SHIP_SPLIT_DEPTH := BEHIND_ROWS

## Every road-geometry material goes through here so all of them carry the
## DOS horizontal cone warp. Vertex colours are the albedo, unshaded, faces
## never culled — the same surface contract the old StandardMaterial3D had.
##   transparent: draw in the transparent pass (blend, no depth write unless
##                depth_always) — used by the cover rows and the overlay
##   depth_always: write depth from the transparent pass (cover rows)
##   no_depth_test: draw over everything (debug overlay)
##   clip: CLIP_NONE, or CLIP_FAR / CLIP_NEAR to keep only the half of the
##         geometry beyond / nearer than SHIP_SPLIT_DEPTH. The ship's own row
##         is drawn twice, once through each, which is how the pre-ship and
##         post-ship passes are reproduced without moving the sprite into the
##         depth buffer.
enum { CLIP_NONE = 0, CLIP_FAR = 1, CLIP_NEAR = 2 }

static func make_dos_material(transparent := false, depth_always := false,
		no_depth_test := false, priority := 0,
		clip := CLIP_NONE) -> ShaderMaterial:
	var modes := "unshaded, cull_disabled"
	if no_depth_test:
		modes += ", depth_test_disabled, depth_draw_never"
	elif depth_always:
		modes += ", depth_draw_always"
	# the halves must partition, not overlap: one side takes the boundary
	# The world is composed into rows 32..137 of the DOS framebuffer and never
	# above: render.c writes into `fb->px + 32*320` and the span records are
	# baked to stay inside that. A 3D camera has no such bound, so a tall block
	# close to the ship projects up into the sky. This clips it in screen space
	# instead — which is what the original's baked bands amount to.
	#
	# It used to be done by painting the backdrop's own top rows back over the
	# 3D from a CanvasLayer. That also painted over the SHIP, which the
	# original draws unclipped (draw_ship bounds x and the cowl, never y), so a
	# high jump had its top sheared off: measured on road 17 t=150, the
	# reference draws 290 ship pixels from row 31 down and the port drew 145
	# from row 35.
	var clip_src := "\tif (SCREEN_UV.y < %f) discard;" % (
		float(SkyRoads.VIEW_TOP) * SkyRoads.PIXEL_ASPECT / SkyRoads.SQUARE_H)
	if clip == CLIP_FAR:
		clip_src += "\n\tif (v_depth < %f) discard;" % SHIP_SPLIT_DEPTH
	elif clip == CLIP_NEAR:
		clip_src += "\n\tif (v_depth >= %f) discard;" % SHIP_SPLIT_DEPTH
	# Surface-ID pass: every quad carries the id of the reference RECORD it
	# claims to be (scripts/app/SurfaceIds.gd) in UV2.x, and when sid_mode is
	# on the fragment paints that id instead of the palette colour. Geometry,
	# clipping and draw order are untouched, so the map is of the frame that
	# would otherwise have been drawn — see BUGS §12.14 for why colour cannot
	# answer the same question.
	var code := "shader_type spatial;\nrender_mode " + modes + ";\n" + """
varying float v_depth;
varying float v_sid;
uniform float sid_mode = 0.0;
void vertex() {
	vec4 v = MODELVIEW_MATRIX * vec4(VERTEX, 1.0);
	float d = max(-v.z, 0.05);
	v_depth = d;
	v_sid = UV2.x;
	float y200 = %f + %f / d;
	float dos_lane = max(%f * (y200 - %f), 0.001);
	float pin_lane = 46.0 * %f / d;
	v.x *= dos_lane / pin_lane;
	// the vertical twin: the original draws raised surfaces flatter with
	// distance than perspective does, and 1:1 at the ship's own depth
	float gd = max(d, %f);
	float tier = max(%f + %f * gd + %f / gd, 0.0);
	v.y = (v.y + %f) * tier - %f;
	POSITION = PROJECTION_MATRIX * v;
}
void fragment() {
%s
	if (sid_mode > 0.5) {
		float sid = floor(v_sid + 0.5);
		ALBEDO = vec3(
			(floor(mod(sid, 8.0)) * 32.0 + 16.0) / 255.0,
			(floor(mod(sid / 8.0, 8.0)) * 32.0 + 16.0) / 255.0,
			(floor(mod(sid / 64.0, 4.0)) * 64.0 + 32.0) / 255.0);
	} else {
		ALBEDO = COLOR.rgb;
	}
%s
}
""" % [DOS_P200, DOS_F200, DOS_LANE_PER_LINE, DOS_X_VANISH_Y, BEHIND_ROWS,
		DOS_TIER_MIN_DEPTH, DOS_TIER_A, DOS_TIER_B, DOS_TIER_C,
		CAMERA_HEIGHT, CAMERA_HEIGHT,
		clip_src, "\tALPHA = COLOR.a;" if transparent else ""]
	var sh := Shader.new()
	sh.code = code
	var mat := ShaderMaterial.new()
	mat.shader = sh
	mat.render_priority = priority
	return mat


## Screen position (in the original's 320x240 display space) to a world point
## at `depth` units in front of the camera.
##
## Godot's project_position() does not stay consistent with this camera's
## off-axis frustum, so this uses the pinhole model directly — the same model
## unproject_position() was checked against.
func screen_to_world(screen: Vector2, depth: float) -> Vector3:
	var s := depth / FOCAL_PX
	return global_position + Vector3(
		(screen.x - PRINCIPAL.x) * s,
		-(screen.y - PRINCIPAL.y) * s,
		-depth)


## World size of a screen-space rectangle at `depth`.
func screen_size_to_world(size: Vector2, depth: float) -> Vector2:
	var s := depth / FOCAL_PX
	return Vector2(size.x * s, size.y * s)


## Convert an original ship position to world space.
static func ship_position(x_units: int, y_units: int, z32: int) -> Vector3:
	var row := float(z32) / 65536.0
	var lane := (float(x_units) - 32768.0) / 5888.0    ## 0x8000 centre, 0x1700/col
	return Vector3(lane * COLUMN_WIDTH,
		(float(y_units) - 10240.0) * WORLD_PER_GAME_Y,
		-row)
